export const GET_MENU_CATEGORIES = "GET_MENU_CATEGORIES";
export const GET_MENU_CATEGORIES_SUCCESS = "GET_MENU_CATEGORIES_SUCCESS";
export const DELETE_MENU_CATEGORY = "DELETE_MENU_CATEGORY";
export const DELETE_MENU_CATEGORY_SUCCESS = "DELETE_MENU_CATEGORY_SUCCESS";
