// Authentication types
export const SIGNUP = 'SIGNUP_USER';
export const SIGNUP_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_USER_ERROR';

export const SIGNIN = 'SIGNIN_USER';
export const SIGNIN_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_USER_ERROR';

export const SIGNOUT = 'SIGNOUT_USER';
export const SIGNOUT_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const SIGNOUT_ERROR = 'SIGNOUT_USER_ERROR';

export const CHECK_AUTH = 'CHECK_AUTH';
export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS';
export const CHECK_AUTH_ERROR = 'CHECK_AUTH_ERROR';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
