export const MODAL_NAMES = {
  SIGN_IN: "SIGN_IN",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  SIGN_UP: "SIGN_UP",
  SIGN_UP_SUCCESS_HELPER: "SIGN_UP_SUCCESS_HELPER",
  CHECK_EMAIL_HELPER: "CHECK_EMAIL_HELPER",
  CREATE_RESTAURANT: "CREATE_RESTAURANT",
};
