export { HomePage } from "./home";
export { RestaurantPage } from "./reastaurant";
export { ProfilePage } from "./profile";
export { MenuPage } from "./menu";
export { PreviewPage } from "./preview";
export { NotFoundPage } from "./notFound";
export { ResetPassswordPage } from "./resetPassword";
export { UserMenuPage } from "./userMenuPage";
export { ActiveMenu } from "./activeMenu";
export { PrivacyPolicyPage } from "./privacyPolicy";
export { TermsConditionsPage } from "./termsConditions";
export { PlansAndPrices } from "./plansAndPrices";

export { RestaurantMenus } from "./restaurantMenus/restaurantMenus";
export { MenusSettings } from "./restaurantMenus/menusSettings/menusSettings";
export { EditMenus } from "./restaurantMenus/editMenus/editMenus";
export { RestaurantSettings } from "./restaurantSettings/restaurantSettings";
export { RestaurantPlansAndPricing } from "./restaurantPlansAndPricing/restaurantPlansAndPricing";
export { RestaurantPayment } from "./restaurantPayment/restaurantPayment";
