export const PROFILE_SIGN_IN = "PROFILE_SIGN_IN";
export const PROFILE_SIGN_IN_SUCCESS = "PROFILE_SIGN_SUCCESS";
export const PROFILE_SIGN_OUT = "PROFILE_SIGN_OUT";
export const GET_USER_INFO = "GET_USER_INFO";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
