export const PROFILE_SIGN_IN = "PROFILE_SIGN_IN";
export const PROFILE_SIGN_IN_SUCCESS = "PROFILE_SIGN_SUCCESS";
export const PROFILE_SIGN_OUT = "PROFILE_SIGN_OUT";
export const GET_PROFILE_INFO = "GET_PROFILE_INFO";
export const GET_PROFILE_INFO_SUCCESS = "GET_PROFILE_INFO_SUCCESS";
export const PROFILE_SIGN_UP = "PROFILE_SIGN_UP";
export const PROFILE_SIGN_UP_SUCCESS = "PROFILE_SIGN_UP_SUCCESS";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
