const initialState = [
	{
		id: "0",
		title: "sdfsadasdfsda",
		description: "sdfsdfsdfsdf sdf asd fas",
		options: "sdsdfsdfsd",
		imageUrl: " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
		type:"foods",
		parents:[],
		price: 888,
	},
	{
		id: "1",
		title: "sdfsadasdfsda",
		description: "sdfsdfsdfsdf sdf asd fas",
		options: "sdsdfsdfsd",
		imageUrl: " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
		type:"foods",
		parents:[],
		price: 888,
	},
	{
		id: "2",
		title: "2sdfsadasdfsda",
		description: "sdfsdfsdfsdf sdf asd fas",
		options: "sdsdfsdfsd",
		imageUrl: " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
		type:"foods",
		parents:[],
		price: 888,
	},
	{
		id: "3",
		title: "3sdfsadasdfsda",
		description: "sdfsdfsdfsdf sdf asd fas",
		options: "sdsdfsdfsd",
		imageUrl: " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
		type:"foods",
		parents:[],
		price: 888,
	},
	{
		id: "4",
		title: "4sdfsad fdfasd asdf asdf asd fasdf asdfa sdfas dfasd asdfsda",
		description: "sdfsdfsdfsdf siu pufpbuxyfpbuycfpbuyxcpfubypixcuyb pcixuyv bixucyvbiuxcyvpbiuycxpviubyxpi uvuicvpiuxcvbiupyx cvpuycxpvbyxpciuv bipuxcvpucvpbuu df asd fas",
		options: "sdsdfsdfsd",
		imageUrl: " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
		type:"foods",
		parents:["879ddf87sdfas9","879ddf8sd79","879ddf8as79"],
		price: 8888,
	},
	{
		id: "5",
		title: "5sdfsadasdfsda",
		description: "sdfsdfsdfsdf sdf asd fas",
		options: "sdsdfsdfsd",
		imageUrl: " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
		type:"foods",
		parents:[],
		price: 888,
	},
	{
		id: "6",
		title: "sdfsadasdfsda",
		description: "sdfsdfsdfsdf sdf asd fas",
		options: "sdsdfsdfsd",
		imageUrl: " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
		type:"foods",
		parents:[],
		price: 888,
	},
	{
		id: "6a",
		title: "sdfsadasdfsda",
		description: "sdfsdfsdfsdf sdf asd fas",
		options: "sdsdfsdfsd",
		imageUrl: " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
		type:"foods",
		parents:[],
		price: 888,
	},
	{
		id: "7",
		title: "sdfsadasdfsda",
		description: "sdfsdfsdfsdf sdf asd fas",
		options: "sdsdfsdfsd",
		imageUrl: " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
		type:"foods",
		parents:[],
		price: 888,
	},
	{
		id: "8",
		title: "sdfsadasdfsda",
		description: "sdfsdfsdfsdf sdf asd fas",
		options: "sdsdfsdfsd",
		imageUrl: " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
		type:"foods",
		parents:[],
		price: 888,
	}, {
		id: "9",
		title: "sdfsadasdfsda",
		description: "sdfsdfsdfsdf sdf asd fas",
		options: "sdsdfsdfsd",
		imageUrl: " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
		type:"foods",
		parents:[],
		price: 888,
	}, {
		id: "10",
		title: "sdfsadasdfsda",
		description: "sdfsdfsdfsdf sdf asd fas",
		options: "sdsdfsdfsd",
		imageUrl: " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
		type:"foods",
		parents:[],
		price: 888,
	}, {
		id: "11",
		title: "sdfsadasdfsda",
		description: "sdfsdfsdfsdf sdf asd fas",
		options: "sdsdfsdfsd",
		imageUrl: " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg"
		,
		price: 888,
	}, {
		id: "12",
		title: "sdfsadasdfsda",
		description: "sdfsdfsdfsdf sdf asd fas",
		options: "sdsdfsdfsd",
		imageUrl: " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
		type:"foods",
		parents:[],
		price: 888,
	}, {
		id: "13",
		title: "sdfsadasdfsda",
		description: "sdfsdfsdfsdf sdf asd fas",
		options: "sdsdfsdfsd",
		imageUrl: " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
		type:"foods",
		parents:[],
		price: 888,
	}, {
		id: "14",
		title: "sdfsadasdfsda",
		description: "sdfsdfsdfsdf sdf asd fas",
		options: "sdsdfsdfsd",
		imageUrl: " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
		type:"foods",
		parents:[],
		price: 888,
	}
]

export const menuItemsReducer = (state = initialState, action) => {
	switch (action.type) {
		
		default:
			return state;
	}
};
