const initialState = [
  {
    id: "0",
    title: "sdfsadasdfsda",
    description: "sdfsdfsdfsdf sdf asd fas",
    options: "sdsdfsdfsd",
    imageUrl: [
      " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
      "",
      "",
      "",
      "",
      "",
    ],
    type: "foods",
    parents: [],
    price: 888,
  },
  {
    id: "1",
    title: "sdfsadasdfsda",
    description: "sdfsdfsdfsdf sdf asd fas",
    options: "sdsdfsdfsd",
    imageUrl: [
      " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
      "",
      "",
      "",
      "",
      "",
    ],
    type: "foods",
    parents: [],
    price: 888,
  },
  {
    id: "2",
    title: "2sdfsadasdfsda",
    description: "sdfsdfsdfsdf sdf asd fas",
    options: "sdsdfsdfsd",
    imageUrl: [
      " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
      "",
      "",
      "",
      "",
      "",
    ],
    type: "foods",
    parents: [],
    price: 888,
  },
  {
    id: "3",
    title: "3sdfsadasdfsda",
    description: "sdfsdfsdfsdf sdf asd fas",
    options: "sdsdfsdfsd",
    imageUrl: [
      " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
      "",
      "",
      "",
      "",
      "",
    ],
    type: "foods",
    parents: [],
    price: 888,
  },
  {
    id: "4",
    title: "4sdfsad fdfasd asdf asdf asd fasdf asdfa sdfas dfasd asdfsda",
    description:
      "sdfsdfsdfsdf siu pufpbuxyfpbuycfpbuyxcpfubypixcuyb pcixuyv bixucyvbiuxcyvpbiuycxpviubyxpi uvuicvpiuxcvbiupyx cvpuycxpvbyxpciuv bipuxcvpucvpbuu df asd fas",
    options: "sdsdfsdfsd",
    imageUrl: [
      " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
      "https://www.picuki.com/app/controllers/proxy_image.php?url=https%3A%2F%2Finstagram.flwo4-1.fna.fbcdn.net%2Fv%2Ft51.2885-15%2Fsh0.08%2Fe35%2Fs640x640%2F176674518_546094916375935_813193530024391261_n.jpg%3Ftp%3D1%26_nc_ht%3Dinstagram.flwo4-1.fna.fbcdn.net%26_nc_cat%3D107%26_nc_ohc%3D4lKh1m8yhaIAX-VrUCl%26edm%3DAA0rjkIAAAAA%26ccb%3D7-4%26oh%3Dc94397209f97d24002a295b1c48bc56e%26oe%3D60AD3DB5%26_nc_sid%3Dd997c6",
      "",
      "",
      "",
      "",
    ],
    type: "foods",
    parents: ["879ddf87sdfas9", "879ddf8sd79", "879ddf8as79"],
    price: 8888,
  },
  {
    id: "5",
    title: "5sdfsadasdfsda",
    description: "sdfsdfsdfsdf sdf asd fas",
    options: "sdsdfsdfsd",
    imageUrl: [
      " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
      "",
      "",
      "",
      "",
      "",
    ],
    type: "foods",
    parents: [],
    price: 888,
  },
  {
    id: "6",
    title: "sdfsadasdfsda",
    description: "sdfsdfsdfsdf sdf asd fas",
    options: "sdsdfsdfsd",
    imageUrl: [
      " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
      "",
      "",
      "",
      "",
      "",
    ],
    type: "foods",
    parents: [],
    price: 888,
  },
  {
    id: "6a",
    title: "sdfsadasdfsda",
    description: "sdfsdfsdfsdf sdf asd fas",
    options: "sdsdfsdfsd",
    imageUrl: [
      " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
      "",
      "",
      "",
      "",
      "",
    ],
    type: "foods",
    parents: [],
    price: 888,
  },
  {
    id: "7",
    title: "sdfsadasdfsda",
    description: "sdfsdfsdfsdf sdf asd fas",
    options: "sdsdfsdfsd",
    imageUrl: [
      " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
      "",
      "",
      "",
      "",
      "",
    ],
    type: "foods",
    parents: [],
    price: 888,
  },
  {
    id: "8",
    title: "sdfsadasdfsda",
    description: "sdfsdfsdfsdf sdf asd fas",
    options: "sdsdfsdfsd",
    imageUrl: [
      " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
      "",
      "",
      "",
      "",
      "",
    ],
    type: "foods",
    parents: [],
    price: 888,
  },
  {
    id: "9",
    title: "sdfsadasdfsda",
    description: "sdfsdfsdfsdf sdf asd fas",
    options: "sdsdfsdfsd",
    imageUrl: [
      " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
      "",
      "",
      "",
      "",
      "",
    ],
    type: "foods",
    parents: [],
    price: 888,
  },
  {
    id: "10",
    title: "sdfsadasdfsda",
    description: "sdfsdfsdfsdf sdf asd fas",
    options: "sdsdfsdfsd",
    imageUrl: [
      " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
      "",
      "",
      "",
      "",
      "",
    ],
    type: "foods",
    parents: [],
    price: 888,
  },
  {
    id: "11",
    title: "sdfsadasdfsda",
    description: "sdfsdfsdfsdf sdf asd fas",
    options: "sdsdfsdfsd",
    imageUrl: [
      " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
      "",
      "",
      "",
      "",
      "",
    ],
    price: 888,
  },
  {
    id: "12",
    title: "sdfsadasdfsda",
    description: "sdfsdfsdfsdf sdf asd fas",
    options: "sdsdfsdfsd",
    imageUrl: [
      " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
      "",
      "",
      "",
      "",
      "",
    ],
    type: "foods",
    parents: [],
    price: 888,
  },
  {
    id: "13",
    title: "sdfsadasdfsda",
    description: "sdfsdfsdfsdf sdf asd fas",
    options: "sdsdfsdfsd",
    imageUrl: [
      " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
      "",
      "",
      "",
      "",
      "",
    ],
    type: "foods",
    parents: [],
    price: 888,
  },
  {
    id: "14",
    title: "sdfsadasdfsda",
    description: "sdfsdfsdfsdf sdf asd fas",
    options: "sdsdfsdfsd",
    imageUrl: [
      " https://www.gastronom.ru/binfiles/images/20151002/bc4c6ff2.jpg",
      "",
      "",
      "",
      "",
      "",
    ],
    type: "foods",
    parents: [],
    price: 888,
  },
];

export const menuItemsReducer = (state = initialState, action) => {
  switch (action.type) {
    default:
      return state;
  }
};
