export const dummyFoodCategories = [
  {
    id: Date.now(),
    name: "Desserts",
    isActive: false,
    products: [
      {
        id: Date.now(),
        name: "Apple pie",
        images: [{ id: Date.now(), url: "" }],
        price: 15,
        isActive: true,
      },
      {
        id: Date.now(),
        name: "Cheesecake",
        images: [{ id: Date.now(), url: "" }],
        price: 15,
        isActive: true,
      },
      {
        id: Date.now(),
        name: "Pecan pie",
        images: [{ id: Date.now(), url: "" }],
        price: 15,
        isActive: true,
      },
      {
        id: Date.now(),
        name: "Carrot cake",
        images: [{ id: Date.now(), url: "" }],
        price: 15,
        isActive: true,
      },
      {
        id: Date.now(),
        name: "Boston cream pie",
        images: [{ id: Date.now(), url: "" }],
        price: 15,
        isActive: true,
      },
      {
        id: Date.now(),
        name: "Banana pudding",
        images: [{ id: Date.now(), url: "" }],
        price: 15,
        isActive: true,
      },
    ],
  },
  {
    id: Date.now(),
    name: "Chinese Food",
    isActive: true,
    products: [
      {
        id: Date.now(),
        name: "Apple pie",
        images: [{ id: Date.now(), url: "" }],
        price: 15,
        isActive: true,
      },
      {
        id: Date.now(),
        name: "Cheesecake",
        images: [{ id: Date.now(), url: "" }],
        price: 15,
        isActive: true,
      },
      {
        id: Date.now(),
        name: "Pecan pie",
        images: [{ id: Date.now(), url: "" }],
        price: 15,
        isActive: true,
      },
    ],
  },
  {
    id: Date.now(),
    name: "Breakfast",
    isActive: true,
    products: [
      {
        id: Date.now(),
        name: "Carrot cake",
        images: [{ id: Date.now(), url: "" }],
        price: 15,
        isActive: true,
      },
    ],
  },
  {
    id: Date.now(),
    name: "Vegan",
    images: [{ id: Date.now(), url: "" }],
    isActive: true,
    products: [],
  },
];
