export const GET_CATEGORY_ITEMS = "GET_CATEGORY_ITEMS";
export const GET_CATEGORY_ITEMS_SUCCESS = "GET_CATEGORY_ITEMS_SUCCESS";
export const ADD_CATEGORY_ITEM = "CREATE_CATEGORY_ITEM";
export const ADD_CATEGORY_ITEM_SUCCESS = "CREATE_CATEGORY_ITEM_SUCCESS";
export const DELETE_CATEGORY_ITEM = "DELETE_CATEGORY_ITEM";
export const DELETE_CATEGORY_ITEM_SUCCESS = "DELETE_CATEGORY_ITEM_SUCCESS";
export const REORDER_CATEGORY_ITEM = "REORDER_CATEGORY_ITEM";
export const REORDER_CATEGORY_ITEM_SUCCESS = "REORDER_CATEGORY_ITEM_SUCCESS";
