export const UPDATE_AVATAR = 'UPDATE_AVATAR';
export const UPDATE_AVATAR_SUCCESS = 'UPDATE_AVATAR_SUCCESS';
export const UPDATE_AVATAR_ERROR = 'UPDATE_AVATAR_ERROR';

export const EDIT_PROFILE = 'UPDATE_PROFILE';
export const EDIT_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const EDIT_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

export const SET_USER = 'SET_USER';
