-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgnudWldrBnimBHaEc
YqU6emQPac1GLs+lrhrgxeyQWkigCgYIKoZIzj0DAQehRANCAAQbtDiYieg0eu92
R75fbrgfAYb7/CesvGbN5SD5qvk2b/U6PyrbCawRZS3jqmRuGwo5IHjaAOUcvvQ8
UskDo5+w
-----END PRIVATE KEY-----